### ISSUE TITLE
SimpleTexture.gltf is not displayed correctly

### ISSUE THREAD

**Issue by cx20** [but0n/Ashes#10]
I tried to display SimpleTexture.gltf of [glTF Tutorials](https://github.com/KhronosGroup/glTF-Tutorials/blob/master/gltfTutorial/gltfTutorial_013_SimpleTexture.md) in Ashes.
However, it seems that it is not displayed correctly.

[Ashes + SimpleTexture.gltf result:](https://rawcdn.githack.com/cx20/gltf-test/0cdde6e7ff886cbba0d76ee87d3bc2593e668575/examples/ashes3d/index.html?category=tutorialModels&model=SimpleTexture&scale=1&type=glTF)
![image](https://user-images.githubusercontent.com/1833979/52562152-dfdb8100-2e40-11e9-8e64-f110097e1376.png)

[three.js + SimpleTexture.gltf result:](https://rawcdn.githack.com/cx20/gltf-test/86007481701925930c9fe7d132139cbf97ccbe0d/examples/threejs/index.html?category=tutorialModels&model=SimpleTexture&scale=1&type=glTF)
![image](https://user-images.githubusercontent.com/1833979/52561993-62b00c00-2e40-11e9-8f4d-9efd2585bfcc.png)

**Comment by but0n** [comment]
Thanks!
I think this is related to #6, I'll fix this soon.

**Comment by but0n** [comment]
![image](https://user-images.githubusercontent.com/7625588/57570368-98f72a80-7433-11e9-99b4-d7cb9a05736c.png)
