### ISSUE TITLE
TextureSettingsTest.gltf has not passed the test

### ISSUE THREAD

**Issue by cx20** [but0n/Ashes#11]
I tried to display [TextureSettingsTest.gltf](https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/TextureSettingsTest) with Ashes.
However, it does not seem to pass some tests.

[Ashes + TextureSettingsTest.gltf result:](https://rawcdn.githack.com/cx20/gltf-test/0cdde6e7ff886cbba0d76ee87d3bc2593e668575/examples/ashes3d/index.html?category=tutorialModels&model=TextureSettingsTest&scale=0.2&type=glTF)
![image](https://user-images.githubusercontent.com/1833979/52562252-4cef1680-2e41-11e9-9a17-eb1f036f225e.png)

**Comment by but0n** [comment]
Thanks!
Added single-sided support at latest version. 
![image](https://user-images.githubusercontent.com/7625588/52617682-a013a880-2ed7-11e9-97d3-28e9a7276e26.png)

**Comment by cx20** [comment]
@but0n Thanks! I confirmed that I passed the test with the latest version.

[Ashes v0.0.24 + TextureSettingsTest.gltf result:](https://rawcdn.githack.com/cx20/gltf-test/309ca9785462ab55e17bb88cbd24453ddfedd67d/examples/ashes3d/index.html?category=tutorialModels&model=TextureSettingsTest&scale=0.2&type=glTF)
![image](https://user-images.githubusercontent.com/1833979/52646821-d62c4900-2f26-11e9-96e6-9a8f37d2bdc9.png)
