### ISSUE TITLE
The orientation of the displayed BrainStem is incorrect

### ISSUE THREAD

**Issue by cx20** [but0n/Ashes#14]
I tried to display [BrainStem](https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/BrainStem) of glTF-Sample-Models with Ashes.
However, it seems that the displayed orientation is incorrect.

[Ashes + BrainStem result:](https://rawcdn.githack.com/cx20/gltf-test/c068c3351e95e9671dc3d815d8466c779b81bfdf/examples/ashes3d/index.html?category=sampleModels&model=BrainStem&scale=1&type=glTF)
![image](https://user-images.githubusercontent.com/1833979/52901308-4ef01580-3245-11e9-9344-91f715f1b873.png)

Expected result:
![image](https://user-images.githubusercontent.com/1833979/52901315-8232a480-3245-11e9-8f79-92034ca6a4a9.png)

**Comment by but0n** [comment]
Thanks for your feedback!
Already fixed in 0.0.37

**Comment by but0n** [comment]
Hang on, seems like the orientation of CesiumMan displayed incorrect after this patch

![image](https://user-images.githubusercontent.com/7625588/52929591-00936180-3380-11e9-8818-045d6b70caae.png)

**Comment by but0n** [comment]
I think this issue is fixed in version 0.0.44.

![image](https://user-images.githubusercontent.com/7625588/53146730-4c444600-35e0-11e9-906f-f678ef2bde56.png)

**Comment by but0n** [comment]
Hi, I've modifed OrbitControl component, now you need manually attach this component to entity.
```js
Ashes.EntityMgr.addComponent(camera, new Ashes.OrbitControl(screen, camera));
```

**Comment by cx20** [comment]
I confirmed that it has been fixed with the latest version of the library.

[Ashes v0.0.44 + BrainStem result:](https://rawcdn.githack.com/cx20/gltf-test/4b161d1693dbaa898a85300f026c2213d777c069/examples/ashes3d/index.html?category=sampleModels&model=BrainStem&scale=1&type=glTF)
![image](https://user-images.githubusercontent.com/1833979/53180433-e89a3700-3638-11e9-8a1f-a1ebf504af95.png)
