### ISSUE TITLE
Polly's skinning animation is incorrect

### ISSUE THREAD

**Issue by cx20** [but0n/Ashes#15]
Project "Polly" is a model created to introduce all the new features of glTF 2.0.
https://github.com/KhronosGroup/glTF-Blender-Exporter/tree/master/polly

However, Ashes does not seem to be able to display Polly correctly yet.
[Ashes + project_polly.gltf result:](https://rawcdn.githack.com/cx20/gltf-test/7dcf25b966201193bf919384e86ab0c941c00f19/examples/ashes3d/index.html?url=https://rawcdn.githack.com/KhronosGroup/glTF-Blender-Exporter/2bd852403600053dba95db78db3f21728b979a7c/polly/project_polly.gltf)
![ashes_polly_004](https://user-images.githubusercontent.com/1833979/53012944-c01f0b00-3487-11e9-9cd8-f78f945ed780.gif)

**Comment by but0n** [comment]
Thanks for your feedback!

It should be fixed in v0.0.46, also #16 
[Ashes + project_polly.gltf result:](https://codepen.io/but0n/pen/qgebQy)

**Comment by cx20** [comment]
I confirmed that v0.0.46 skinning animation problem has been solved.
[Ashes v0.0.46 + project_polly.gltf result:](https://rawcdn.githack.com/cx20/gltf-test/63cb6555f5ab9a29b5a2f23e586ed72c35d2d88a/examples/ashes3d/index.html?url=https://rawcdn.githack.com/KhronosGroup/glTF-Blender-Exporter/2bd852403600053dba95db78db3f21728b979a7c/polly/project_polly.gltf)
![ashes_polly_005](https://user-images.githubusercontent.com/1833979/53282581-1ab4b180-377d-11e9-8cf2-8076a9e9527e.gif)

The nameplate is not displayed, but I think this is another issue.
