### ISSUE TITLE
How to switch between multiple cameras embedded into glTF?

### ISSUE THREAD

**Issue by cx20** [but0n/Ashes#17]
I know that [VC.gltf](https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/VC) and [project_polly.gltf](https://github.com/KhronosGroup/glTF-Blender-Exporter/tree/master/polly) have cool cameras built in them.
However, I do not know how to use them in this library.
Can you add samples if possible?

https://www.youtube.com/watch?v=l7TB1O51X_M

**Comment by but0n** [comment]
Currently, this library havn't parsing cameras information, but you can still implement this by attach the camera entity you already created to the target node at scene.

[Example based on v0.0.47](https://codepen.io/but0n/pen/PVMWWO)
*Seems like the angle of view is incorrect.*

- Create a camera entity and load gltf scene
```js
    // Camera and controls
    let mainCamera = EntityMgr.create('camera');
    let cameraTrans = mainCamera.components.Transform;
    let cam = EntityMgr.addComponent(mainCamera, new Camera(screen.width / screen.height));

    vec3.set(cameraTrans.translate, 0, 0, 0.1); // set a little bit z offset to allow you orbit around

    EntityMgr.addComponent(mainCamera, new OrbitControl(screen, mainCamera));

    let gltfroot = await Asset.loadGLTF(gltf, screen, skybox);
    scene.appendChild(gltfroot);
    let root = gltfroot.components.Transform;
    root.translate[1] = yoffset || 0;
    vec3.scale(root.scale, root.scale, scale || 200)
```

- find a node, attach camera
```js
    let movingTarget = document.querySelectorAll('[data-name=Correction__MovingCamera]')[0];

    movingTarget.appendChild(mainCamera);
  
    EntityMgr.hasNewMember = true;
```

**Comment by cx20** [comment]
@but0n Thanks to your advice I was able to try out the camera embedded in the Polly model. 
[Ashes v0.0.47 + project_polly result](https://rawcdn.githack.com/cx20/gltf-test/e6742ff731baed1f17ae4f7cf50fc71aefe1b6fa/examples/ashes3d/index.html?url=https://rawcdn.githack.com/KhronosGroup/glTF-Blender-Exporter/2bd852403600053dba95db78db3f21728b979a7c/polly/project_polly.glb)

BTW, I tried the same thing with `VC.gltf`, but I could not find the camera.
Is it because the camera name is not set?
![image](https://user-images.githubusercontent.com/1833979/53289564-d7892b80-37da-11e9-9087-593ec5d8f1a1.png)

**Comment by but0n** [comment]
Actually, the value of `data-name` is related with the `nodes[n].name`, not the camera name.

If the target node doesn’t has a name, it could be difficult to query the entity of target, unless you specify a name by modifying the glTF file.

**Comment by cx20** [comment]
I understand that I am using a node name instead of a camera name.

I tried several other WebGL libraries for reference.
It seems that if you do not set the node name or the camera name, it is automatically assigned numbers.

Below is example of three.js.

[three.js + Polly model result:](https://gltf-viewer.donmccurdy.com/?#model=https://rawcdn.githack.com/KhronosGroup/glTF-Blender-Exporter/2bd852403600053dba95db78db3f21728b979a7c/polly/project_polly.glb)
![image](https://user-images.githubusercontent.com/1833979/53297526-1236a680-3863-11e9-9715-01a99eb0be1c.png)

[thre.js + VC.gltf result:](https://gltf-viewer.donmccurdy.com/?#model=https://rawcdn.githack.com/cx20/gltf-test/55635899b8646b3b90fbd483d0df036fb9b50c0c/sampleModels/VC/glTF/VC.gltf)
![image](https://user-images.githubusercontent.com/1833979/53297568-9852ed00-3863-11e9-9f7c-1d32a3ce9983.png)

Below is example of Babylon.js. 

[Babylon.js + Polly model resultl:](https://sandbox.babylonjs.com/?assetUrl=https://rawcdn.githack.com/KhronosGroup/glTF-Blender-Exporter/2bd852403600053dba95db78db3f21728b979a7c/polly/project_polly.glb)
![image](https://user-images.githubusercontent.com/1833979/53297349-e87c8000-3860-11e9-9628-b61609a83f71.png)

[Babylon.js + VC.gltf result:](https://sandbox.babylonjs.com/?assetUrl=https://rawcdn.githack.com/cx20/gltf-test/55635899b8646b3b90fbd483d0df036fb9b50c0c/sampleModels/VC/glTF/VC.gltf)
![image](https://user-images.githubusercontent.com/1833979/53297396-cafbe600-3861-11e9-8ecd-053694b1f9f8.png)

**Comment by but0n** [comment]
That will be useful!
I will add this feature in next version.

**Comment by cx20** [comment]
I confirmed that Ashes `v0.0.49` will display nodes with no names.
![image](https://user-images.githubusercontent.com/1833979/53498730-3c4dca00-3aea-11e9-99e3-ad9f43c4bba9.png)
However, I do not know which node the camera is tied to, so I'm happy if there is a way to know.

**Comment by but0n** [comment]
Now you can query those cameras and set one of them as main camera:

![image](https://user-images.githubusercontent.com/7625588/53680625-13f7e280-3d19-11e9-8efd-fba4086ad976.png)

```js
// screen  = Ashes.Screen.list['#screen']
screen.mainCamera = Ashes.EntityMgr.getComponents('Camera')[2]
```

![image](https://user-images.githubusercontent.com/7625588/53680602-dd21cc80-3d18-11e9-81af-58bc53328215.png)

**Comment by cx20** [comment]
@but0n Thank you for support of the camera. I modified the [gltf-test](https://github.com/cx20/gltf-test) sample so that I switch the camera at regular intervals.

[Ashes + VC.gltf + camera sample](https://rawcdn.githack.com/cx20/gltf-test/266837505ec08134a397670d997c426e303c282e/examples/ashes3d/index.html?category=sampleModels&model=VC&scale=0.2&type=glTF)
```javascript
let cameras =  Ashes.EntityMgr.getComponents('Camera');
if ( cameras.length > 0 ) {
    setInterval(function(){
        let cameraIndex = Math.floor(cameras.length * Math.random());
        screen.mainCamera = cameras[cameraIndex];
    }, 5000);
}
```
