### ISSUE TITLE
Bear's model is not displayed correctly

### ISSUE THREAD

**Issue by cx20** [but0n/Ashes#19]
I tried to display the model of the bear published in sketchfab using Ashes.
However, only one balloon was displayed and no bear was displayed.

Ashes + Bear model result:
http://jsdo.it/cx20/wPO4
![image](https://user-images.githubusercontent.com/1833979/53295186-5745e300-3839-11e9-86ef-30b2221f6870.png)

Below is the expected display result.

three.js + Bear model result:
http://jsdo.it/cx20/6MMO
![image](https://user-images.githubusercontent.com/1833979/53295198-88261800-3839-11e9-9919-1c3188f7a230.png)

**Comment by but0n** [comment]
Thanks for your feedback!
I saw this model before, I think it is probably related to the special skeleton.

It’ll be fixed in next version.

https://github.com/KhronosGroup/glTF/pull/1195#issuecomment-368632227

**Comment by but0n** [comment]
![image](https://user-images.githubusercontent.com/7625588/53309317-2bcb0300-38e2-11e9-8327-080429cb1227.png)
I think it should be fixed in commit #10dbf61

**Comment by cx20** [comment]
I confirmed that bears and balloons will be displayed in Ashes `v0.0.49`.
[Ashes v0.0.49 + Bear model result:](http://jsdo.it/cx20/CvPa)
http://jsdo.it/cx20/CvPa
![image](https://user-images.githubusercontent.com/1833979/53494383-fb9d8300-3ae0-11e9-95cd-adad890d4f7b.png)
