### ISSUE TITLE
Please support glTF-Embedded format

### ISSUE THREAD

**Issue by cx20** [but0n/Ashes#20]
I tried to display several glTF models using Ashes.
However, it seems that you can not display models in `glTF Embedded` format.
The following is a sample that could not be displayed because of a format problem.

Ashes + glTF Additonal Test Case No.3
http://jsdo.it/cx20/kSsC

Ashes + glTF Additonal Test Case No.5
http://jsdo.it/cx20/YY6E

Ashes + glTF Additonal Test Case No.10
http://jsdo.it/cx20/c2TU

The `glTF Embedded format` is a format used when incorporating resources into JSON using `Data URI`.
I hope that you can support if possible.

**Comment by cx20** [comment]
Perhaps, if you check in the following places if the `uri` format is a `Data URI` and set `uri` or `root + uri`, I think that it will be displayed.
https://github.com/but0n/Ashes/blob/master/src/asset.ts#L137-L146

**Comment by cx20** [comment]
The following is a suggestion of a fix code.

```typescript
static adjustDataUri(root, uri) {
    return uri.substr(0, 5) == "data:" ? uri : root + uri;
}

//gltf.buffers = await Promise.all(gltf.buffers.map(({ uri }) => this.loadBuffer(root + uri)));
gltf.buffers = await Promise.all(gltf.buffers.map(({ uri }) => this.loadBuffer(adjustDataUri(root, uri))));

//gltf.images = await Promise.all(gltf.images.map(({ uri }) => this.loadImage(root + uri)));
gltf.images = await Promise.all(gltf.images.map(({ uri }) => this.loadImage(adjustDataUri(root, uri))));
```

**Comment by but0n** [comment]
Thanks for your suggestion!
I'm already add the fix code you provide, it will support data url in the next version.

**Comment by cx20** [comment]
I tried `v0.0.48`. However, it seems that there is another error.
```
ashes.main.js:5711 
Uncaught TypeError: meshChunk.entities(...) is not a function or its return value is not iterable
    at gltfScene.createEntity (ashes.main.js:5711)
    at setTimeout (ashes.main.js:5623)
```

![image](https://user-images.githubusercontent.com/1833979/53419972-38ed0c80-3a1e-11e9-9422-830fffed738f.png)

**Comment by but0n** [comment]
Oh, that was a typo. 😅
It already been fixed in the newest version.

**Comment by cx20** [comment]
@but0n I updated the status of [gltf-test](https://github.com/cx20/gltf-test#format-tests) by confirming that `glTF Embedded` format can be displayed with Ashes `v0.0.49`.
![image](https://user-images.githubusercontent.com/1833979/53493720-5cc45700-3adf-11e9-898c-1e0d00b35b05.png)

Also updated the sample in jsdo.it. Since there are some samples that can not be displayed yet, I will report it as a separate Issue.
