### ISSUE TITLE
glTF model without Indices is not displayed

### ISSUE THREAD

**Issue by cx20** [but0n/Ashes#22]
I tried to display the glTF file output from [Three.js glTF Exporter](http://jsdo.it/cx20/CDcF) with Ashes.
However, Ashes does not seem to be able to display that model.
Perhaps I think that Ashes does not correspond to the glTF model without Indices.

Ashes + glTF Additonal Test Case No.5
http://jsdo.it/cx20/YY6E

Below is the expected result.
[three.js + VoxelCorgi.gltf result:](http://jsdo.it/cx20/ahsW)
http://jsdo.it/cx20/ahsW
![image](https://user-images.githubusercontent.com/1833979/53644426-ed369f00-3c79-11e9-8ff2-1975aa156172.png)

**Comment by but0n** [comment]
I think the glTF model without Indices is already supported right now.
Can you provide this glTF file? I need to test the vertices color.
Thanks!

**Comment by cx20** [comment]
Below, it will be test data and sample.
https://cx20.github.io/gltf-test/examples/ashes3d/index.html?url=https://rawcdn.githack.com/cx20/jsdo-static-contents/ef789b017e86ed960bd38df4617fadbbfbd245ec/models/gltf/2.0/VoxelCorgi/glTF_merge/VoxelCorgi.gltf

```
ashes.main.js:5523 
Uncaught (in promise) TypeError: Cannot read property 'bufferView' of undefined
    at mesh.primitives.map.meshData (ashes.main.js:5523)
    at Array.map (<anonymous>)
    at gltf.meshes.gltf.meshes.map.mesh (ashes.main.js:5501)
    at Array.map (<anonymous>)
    at new gltfScene (ashes.main.js:5500)
    at Function.<anonymous> (ashes.main.js:5936)
    at Generator.next (<anonymous>)
    at fulfilled (ashes.main.js:5203)
```

![image](https://user-images.githubusercontent.com/1833979/53826707-a2d85980-3fbc-11e9-999c-68f2dd9dd139.png)

**Comment by but0n** [comment]
Is this correct?

![image](https://user-images.githubusercontent.com/7625588/53862030-eb296300-4020-11e9-8008-efac850a876b.png)

**Comment by cx20** [comment]
Yes. It looks good.
I would like to confirm it again when a new version is released.

**Comment by but0n** [comment]
Hi, a new version is released!

In version 0.1.0 you can adding component to entity with alias:
```js
// EntityMgr.addComponent(entity, component);
entity.addComponent(component);
```

**Comment by cx20** [comment]
I confirmed that this model will be displayed in Ashes v0.1.0.
[Ashes v0.1.0 + VoxelCorgi.gltf result:](https://rawcdn.githack.com/cx20/gltf-test/c653321e95da7a7dc83aa98924f18b490f905413/examples/ashes3d/index.html?url=https://rawcdn.githack.com/cx20/jsdo-static-contents/ef789b017e86ed960bd38df4617fadbbfbd245ec/models/gltf/2.0/VoxelCorgi/glTF_merge/VoxelCorgi.gltf&scale=0.05)
![image](https://user-images.githubusercontent.com/1833979/54036446-f9cd7100-41fe-11e9-880a-f3ff4cbe9633.png)
I would like to try out the function of the component later.
