### ISSUE TITLE
Color of PrimaryIonDrive.glb displayed differs from expected

### ISSUE THREAD

**Issue by cx20** [but0n/Ashes#23]
I tried to display the sample [PrimaryIonDrive](https://blog.sketchfab.com/art-spotlight-primary-ion-drive/) in Sketchfab with Ashes.
However, the display result seems to be different from the assumed.

Ashes + PrimaryIonDrive.glb result:
http://jsdo.it/cx20/ETNa
![image](https://user-images.githubusercontent.com/1833979/53677056-76d38480-3ced-11e9-8c1e-094b6c557fea.png)

three.js + PrimaryIonDrive.glb result:
http://jsdo.it/cx20/0kU1
![image](https://user-images.githubusercontent.com/1833979/53677066-98347080-3ced-11e9-9c81-6f862b0a4bc1.png)

Is it because it does not support [vertex colors](https://cx20.github.io/gltf-test/examples/ashes3d/index.html?category=tutorialModels&model=VertexColorTest&scale=1.0&type=glTF)?

**Comment by but0n** [comment]
Yeah, it doesn't support vertex colors yet.

**Comment by but0n** [comment]
Thanks for your feedback!

I think it should be fixed.
![image](https://user-images.githubusercontent.com/7625588/53862221-96d2b300-4021-11e9-9f6b-f057c44ee95e.png)

**Comment by cx20** [comment]
I confirmed that the color of this model is displayed correctly with Ashes v0.1.0.
[Ashes v0.1.0 + PrimaryIonDrive.glb result:](https://rawcdn.githack.com/cx20/gltf-test/c653321e95da7a7dc83aa98924f18b490f905413/examples/ashes3d/index.html?url=https://cdn.rawgit.com/mrdoob/three.js/dev/examples/models/gltf/PrimaryIonDrive.glb)
![image](https://user-images.githubusercontent.com/1833979/54036732-b32c4680-41ff-11e9-89a3-8dc2251fd578.png)

**Comment by cx20** [comment]
I confirmed that the sample model of the `vertex color` below is also displayed. I have updated the status of [gltf-test](https://github.com/cx20/gltf-test).

[Ashes v0.1.0 + BoxVertexColors.gltf result:](https://cx20.github.io/gltf-test/examples/ashes3d/index.html?model=BoxVertexColors&scale=1)
![image](https://user-images.githubusercontent.com/1833979/54072699-c99ad680-42c1-11e9-9120-3d5d85231998.png)

[Ashes v0.1.0 + VertexColor.gltf result:](https://cx20.github.io/gltf-test/examples/ashes3d/index.html?category=tutorialModels&model=VertexColorTest&scale=1.0&type=glTF)
![image](https://user-images.githubusercontent.com/1833979/54072705-db7c7980-42c1-11e9-86f0-23cc9ef7c68b.png)
