### ISSUE TITLE
Sample of GitHub Pages is not displayed due to an error

### ISSUE THREAD

**Issue by cx20** [but0n/Ashes#25]
I tried to display the following page.
https://but0n.github.io/Ashes/

However, an error is output to the console and the page is not displayed.
```
(index):68 
Uncaught (in promise) TypeError: mainCamera.addComponent is not a function
    at main ((index):68)
```
![image](https://user-images.githubusercontent.com/1833979/54042929-a9f6a600-420e-11e9-866a-0aa54841eb49.png)

**Comment by but0n** [comment]
Thanks for your feedback!
It has been updated to the correct version.
