### ISSUE TITLE
FlightHelmet's goggles do not pass through properly

### ISSUE THREAD

**Issue by cx20** [but0n/Ashes#26]
I tried to display the model of FlightHelmet.
There was almost no problem, but there was a place that I was a bit worried about.

[Ashes + FlightHelmet result:](https://rawcdn.githack.com/cx20/gltf-test/c653321e95da7a7dc83aa98924f18b490f905413/examples/ashes3d/index.html?category=tutorialModels&model=FlightHelmet&scale=5&type=glTF)

Example with lenses: I can _not_ see the prop inside the helmet.
![image](https://user-images.githubusercontent.com/1833979/54072414-bf76d900-42bd-11e9-9b6e-5c79064e3f18.png)

Example _without_ a lens:  I can see the prop inside the helmet.
![image](https://user-images.githubusercontent.com/1833979/54072417-d1587c00-42bd-11e9-83b5-ce89d8ae52ea.png)

If the lens passes through correctly, I think that it is the correct display result that you can see the prop inside the helmet.

**Comment by but0n** [comment]
Thanks for your feedback!
This is related to #27 , because the order of render queue is incorrect.
I will handle this soon.

**Comment by cx20** [comment]
I confirmed that this issue has been fixed in Ashes v0.1.1. It's a great job.
[Ashes v0.1.1 + FlightHelmet.gltf result:](https://rawcdn.githack.com/cx20/gltf-test/f345c1e9ce63a5d2426666fa61aec48d6d92f5c1/examples/ashes3d/index.html?category=tutorialModels&model=FlightHelmet&scale=0.5&txype=glTF&scale=5)
![image](https://user-images.githubusercontent.com/1833979/54284706-c7978700-45e3-11e9-84f4-3d554934e6de.png)
