### ISSUE TITLE
Alpha Blend test has not passed

### ISSUE THREAD

**Issue by cx20** [but0n/Ashes#27]
I tried to display [AlphaBlendModeTest.gltf](https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/AlphaBlendModeTest/glTF).
However, the case of Blend does not seem to pass.

[Ashes + AlphaBlendModeTest.gltf result:](https://cx20.github.io/gltf-test/examples/ashes3d/index.html?category=tutorialModels&model=AlphaBlendModeTest&scale=0.5&type=glTF)
![image](https://user-images.githubusercontent.com/1833979/54072833-70cc3d80-42c3-11e9-9913-c5d8b1832d04.png)

The following is the expected result.
https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/AlphaBlendModeTest
![image](https://user-images.githubusercontent.com/1833979/54072838-93f6ed00-42c3-11e9-8280-415bb8bb19aa.png)

**Comment by but0n** [comment]
Thanks for your feedback!
I think it should be fixed in v0.1.1

![image](https://user-images.githubusercontent.com/7625588/54252606-7311ee80-4586-11e9-8221-bfe122969435.png)

#26 
![image](https://user-images.githubusercontent.com/7625588/54252668-a785aa80-4586-11e9-91bb-2069643d2a63.png)

**Comment by cx20** [comment]
I confirmed that I passed the test with Ashes v0.1.1.
[Ashes v0.1.1 + AlphaBlendTest.gltf result:](https://rawcdn.githack.com/cx20/gltf-test/f345c1e9ce63a5d2426666fa61aec48d6d92f5c1/examples/ashes3d/index.html?category=tutorialModels&model=AlphaBlendModeTest&scale=0.5&type=glTF)

![image](https://user-images.githubusercontent.com/1833979/54284381-2d374380-45e3-11e9-8b36-92d651e60b0a.png)
