### ISSUE TITLE
MorphPrimitivesTest.gltf is not displayed as expected

### ISSUE THREAD

**Issue by cx20** [but0n/Ashes#28]
I tried to display [MorphPrimitivesTest.gltf](https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/MorphPrimitivesTest).
However, it does not seem to be the expected display result.

[Ashes + MorphPrimitivesTest.gltf result:](https://rawcdn.githack.com/cx20/gltf-test/eef6b5b62faf7bfefc6eb3303261e99be1270e9d/examples/ashes3d/index.html?category=tutorialModels&model=MorphPrimitivesTest&scale=2&type=glTF)
![image](https://user-images.githubusercontent.com/1833979/54072967-e7b60600-42c4-11e9-904e-373256793f34.png)

The following is the expected display result.
https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/MorphPrimitivesTest
![image](https://user-images.githubusercontent.com/1833979/54072971-eedd1400-42c4-11e9-9464-67c52db7c387.png)

**Comment by but0n** [comment]
Thanks for your feedback, I think it should be fixed in v0.2.0:

![image](https://user-images.githubusercontent.com/7625588/55290339-a2d54900-5404-11e9-9794-d34aaf25908e.png)

**Comment by cx20** [comment]
I confirmed that this model is correctly displayed in Ashes v0.2.0.
[Ashes v0.2.0 + MorphPrimitivesTest.gltf result:](https://rawcdn.githack.com/cx20/gltf-test/6e9cd5f169de324dc28d1f86789545cc366f2334/examples/ashes3d/index.html?category=tutorialModels&model=MorphPrimitivesTest&scale=2&type=glTF)

![image](https://user-images.githubusercontent.com/1833979/55290834-40377980-5413-11e9-8130-b07b2e71bd8c.png)
