### ISSUE TITLE
Triangle.gltf does not displayed

### ISSUE THREAD

**Issue by cx20** [but0n/Ashes#3]
I tried to display [Triangle.gltf](https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/Triangle) with Ashes.
However, an error was output to the console and it was not displayed.

[Ashes v0.0.16 + Triangle.gltf result:](https://rawcdn.githack.com/cx20/gltf-test/57f3ba662ab83e830e78d5416cb1246d43ba2d85/examples/ashes3d/index.html?category=tutorialModels&model=Triangle&scale=1&type=glTF)
```
ashes.main.js:5270 Uncaught (in promise) TypeError: Cannot read property 'map' of undefined
    at Function.<anonymous> (ashes.main.js:5270)
    at Generator.next (<anonymous>)
    at fulfilled (ashes.main.js:860)
```

I think that it is probably failing to display about models that do not have textures.

**Comment by but0n** [comment]
Thanks!
I'll fix it soon.

**Comment by cx20** [comment]
I confirmed that [Triangle.gltf](https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/Triangle) will be displayed.
[Ashes v0.0.17 + Triangle.gltf result:](https://rawcdn.githack.com/cx20/gltf-test/dc122bc9b890004629f3e2eb5f14314c38d23268/examples/ashes3d/index.html?category=tutorialModels&model=Triangle&scale=1&type=glTF)
![image](https://user-images.githubusercontent.com/1833979/51783822-19df2e80-2183-11e9-9884-133cb8928a99.png)

**Comment by but0n** [comment]
Thanks!
