### ISSUE TITLE
brdfLUT.png is 404 Not Found

### ISSUE THREAD

**Issue by cx20** [but0n/Ashes#30]
The following files do not exist at present.

https://github.com/but0n/Ashes/blob/master/src/asset.ts#L189

```
https://raw.githubusercontent.com/KhronosGroup/glTF-WebGL-PBR/master/textures/brdfLUT.png
```

I think the new place is below.
```
https://raw.githubusercontent.com/KhronosGroup/glTF-Sample-Viewer/master/assets/images/brdfLUT.png
```

**Comment by but0n** [comment]
Thanks for your feedback!
It should be fixed in the latest version.

**Comment by cx20** [comment]
I confirmed that it has been fixed in the latest version.
![image](https://user-images.githubusercontent.com/1833979/57577296-c6cd8500-74ae-11e9-8fd5-2f5ed7c2dd45.png)
