### ISSUE TITLE
Loading glTF file seems to fail in Ashes v0.2.3

### ISSUE THREAD

**Issue by cx20** [but0n/Ashes#32]
I tried to display Duck.gltf in Ashes v0.2.3.
However, the following error seems to be displayed.
![image](https://user-images.githubusercontent.com/1833979/59232429-4752e300-8c1f-11e9-8d35-8d3c97309ff8.png)

```
ashes.main.js:4313 Uncaught (in promise) TypeError: Cannot read property 'NORMAL' of undefined
    at Function.bindAccessorsVBO (ashes.main.js:4313)
    at Function.updateVAO (ashes.main.js:5060)
    at Function.attachMaterial (ashes.main.js:5044)
    at new MeshRenderer (ashes.main.js:4966)
    at Function.<anonymous> (ashes.main.js:6061)
    at Generator.next (<anonymous>)
    at fulfilled (ashes.main.js:5301)
```

**Comment by but0n** [comment]
Thanks for your feedback!
It should be fixed in v0.2.4.

**Comment by cx20** [comment]
I confirmed in Ashes v0.2.4 that the above error has been eliminated.

However, there seems to be another problem. The console outputs a WebGL warning and the duck appears and disappears every few seconds.
Should I report it as another issue?
![image](https://user-images.githubusercontent.com/1833979/59302863-e6cfae80-8ccf-11e9-84a6-dee5b62b4ba8.png)

**Comment by but0n** [comment]
It is weird seems like only the duck model has such issues, the others works fine.

Yeah, you can open another issue for this.

**Comment by cx20** [comment]
I reported about Duck issues in #33
