### ISSUE TITLE
jsdo.it is scheduled to end service at the end of October

### ISSUE THREAD

**Issue by cx20** [but0n/Ashes#36]
Unfortunately, [jsdo.it](http://jsdo.it/blog/2019/07/jsdoit-1.html) will be terminated at the end of October.
I ported the jsdo.it sample to github. I'm sorry, but please change the link destination.
http://jsdo.it/tag/Ashes
https://cx20.github.io/jsdo.it-archives/tag/ashes/

**Comment by but0n** [comment]
Thank you very much.
