### ISSUE TITLE
MetalRoughSpheresNoTextures model is not displayed correctly

### ISSUE THREAD

**Issue by cx20** [but0n/Ashes#39]
I tried to display [MetalRoughSpheresNoTextures.gltf](https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/MetalRoughSpheresNoTextures) using the latest version of Ashes.

However, the spheres in the MetalRoughSpheresNoTextures model all look the same.
[MetalRoughSpheresNoTextures.gltf + Ashes result:](https://cx20.github.io/gltf-test/examples/ashes3d/index.html?category=tutorialModels&model=MetalRoughSpheresNoTextures&scale=200&type=glTF)
![image](https://user-images.githubusercontent.com/1833979/69434553-3cc97780-0d81-11ea-8be3-4e2132fdda73.png)

This model is expected to have the same results as MetalRoughSpheres.
[MetalRoughSpheres.gltf + Ashes result:](https://cx20.github.io/gltf-test/examples/ashes3d/index.html?category=tutorialModels&model=MetalRoughSpheres&scale=0.2&type=glTF)
![image](https://user-images.githubusercontent.com/1833979/69434746-929e1f80-0d81-11ea-85fd-0b73c81600e4.png)

**Comment by but0n** [comment]
Thanks for your feedback!
This problem should be fixed in the latest version. Compares to the other engines, current PBR material still has certain problems. I will review the shader in the next version.

![image](https://user-images.githubusercontent.com/7625588/69442745-11965680-0d88-11ea-86e6-5c33442d1de0.png)

**Comment by cx20** [comment]
I have confirmed that this issue has been improved with the latest version of Ashes.

[MetalRoughSpheresNoTextures.gltf + Ashes v0.2.6 result:](https://rawcdn.githack.com/cx20/gltf-test/48e7371878cdc318d209f2b5007b09f6c4a31c9b/examples/ashes3d/index.html?category=tutorialModels&model=MetalRoughSpheresNoTextures&scale=200&type=glTF)
![image](https://user-images.githubusercontent.com/1833979/69449720-dc493300-0d9e-11ea-9501-a87799fcad6c.png)

[MetalRoughSpheres.gltf + Ashes v0.2.6 result:](https://rawcdn.githack.com/cx20/gltf-test/48e7371878cdc318d209f2b5007b09f6c4a31c9b/examples/ashes3d/index.html?category=tutorialModels&model=MetalRoughSpheres&scale=0.2&type=glTF)
![image](https://user-images.githubusercontent.com/1833979/69449825-19152a00-0d9f-11ea-9eaa-a56f04aa37b0.png)
