### ISSUE TITLE
The color of Box.gltf is different from the assumed

### ISSUE THREAD

**Issue by cx20** [but0n/Ashes#4]
I tried displaying [Box.gltf](https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/Box) with the latest library.
However, it is different from the expected color.
[Ashes v0.0.17 + Box.gltf result:](https://rawcdn.githack.com/cx20/gltf-test/dc122bc9b890004629f3e2eb5f14314c38d23268/examples/ashes3d/index.html?category=sampleModels&model=Box&scale=1&type=glTF)
![image](https://user-images.githubusercontent.com/1833979/51783900-5b240e00-2184-11e9-8a28-351952b1f637.png)

The following are assumed results.
![image](https://user-images.githubusercontent.com/1833979/51783914-a2120380-2184-11e9-80ee-be145c4e10ac.png)

**Comment by but0n** [comment]
## glTF Rendering error while material involve empty textures or contains factors

![image](https://user-images.githubusercontent.com/7625588/51783894-ec42b700-217b-11e9-88bf-cf573efbd05e.png)

![image](https://user-images.githubusercontent.com/7625588/51783899-f664b580-217b-11e9-9b62-a13526da88c0.png)

![image](https://user-images.githubusercontent.com/7625588/51783901-fe245a00-217b-11e9-800e-808f3e5bae3a.png)

![image](https://user-images.githubusercontent.com/7625588/51783892-e3ea7c00-217b-11e9-8bb8-5bb42ebeb33f.png)

**Comment by cx20** [comment]
Thank you for quick response.
[Ashes v0.0.18 + Box.gltf result:](https://rawcdn.githack.com/cx20/gltf-test/94806eeafcc8595dbca56bc8b9e15d6959339f5a/examples/ashes3d/index.html?category=sampleModels&model=Box&scale=1&type=glTF)
![image](https://user-images.githubusercontent.com/1833979/51784138-f4085880-2187-11e9-9b26-dec4622fbe7e.png)

I will update the status of [gltf-test](https://github.com/cx20/gltf-test) soon.

**Comment by cx20** [comment]
BTW, in my sample the background is not displayed and it is white. Is the usage incorrect?

**Comment by cx20** [comment]
I updated the status of [gltf-test](https://github.com/cx20/gltf-test) earlier.
I close this Issue because I think that the problem of [Box.gltf](https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/Box) has been solved.
