### ISSUE TITLE
The version of Ashes used in GitHub Pages index.html seems to be old

### ISSUE THREAD

**Issue by cx20** [but0n/Ashes#47]
I tried to display the following page.

https://but0n.github.io/Ashes/index.html

However, the model was not displayed due to an error in the console. I think it's probably due to an old version.

```html
<script src="https://cdn.jsdelivr.net/npm/ashes3d@0.1.0/build/ashes.main.js"></script>
```

**Comment by but0n** [comment]
Thanks for your feedback! This page has been updated.

**Comment by cx20** [comment]
Thanks!
