### ISSUE TITLE
WebGL context is lost when trying to display models with many vertices

### ISSUE THREAD

**Issue by cx20** [but0n/Ashes#5]
I tried to display some samples with Ashes v0.0.18.
However, it seems to fail when trying to display the model of the number of vertices.
```
WebGL: CONTEXT_LOST_WEBGL: loseContext: context lost
```

|Model name|result|
|:-----|:-----:|
|Cylinder Engine|:white_check_mark:|
|Reciprocating Saw|:x:|
|Gearbox Assy|:x:|
|Buggy|:x:|

**Comment by cx20** [comment]
I tried the following environment.
ThinkPad X260 + Intel(R) HD Graphics 520 + Windows 10 + Chrome 71

**Comment by but0n** [comment]
Thanks for your feedback!

 - Buggy
![image](https://user-images.githubusercontent.com/7625588/52556753-70f22e00-2e28-11e9-9833-25e353cd1200.png)

 - Reciprocating Saw
![image](https://user-images.githubusercontent.com/7625588/52556837-9f700900-2e28-11e9-994d-fae78f483369.png)

 - Gearbox Assy
![image](https://user-images.githubusercontent.com/7625588/52556865-b9a9e700-2e28-11e9-9572-2f130eff3aa8.png)

**Comment by cx20** [comment]
@but0n  Thank you for fixing. I confirmed that it will be displayed for the three models above.
However, it seems that another model is no longer displayed.

[Ashes v0.0.22 + CesiumMilkTruck.gltf result:](https://rawcdn.githack.com/cx20/gltf-test/5c51685d63ad22d41893da24b8742a7491522814/examples/ashes3d/index.html?category=sampleModels&model=CesiumMilkTruck&scale=0.5&type=glTF)
![image](https://user-images.githubusercontent.com/1833979/52558402-9fc2d100-2e35-11e9-9b73-eb9a6709b976.png)

Maybe the usage of the library has changed?

**Comment by but0n** [comment]
Thanks! That was a mistake of texture handler.
![image](https://user-images.githubusercontent.com/7625588/52561038-2aef9700-2e35-11e9-89b1-e41fcdcf09c0.png)

**Comment by cx20** [comment]
I confirmed that the above problem was solved with the latest version of the library.

[Ashes v0.0.23 + Buggy.gltf result:](https://rawcdn.githack.com/cx20/gltf-test/0cdde6e7ff886cbba0d76ee87d3bc2593e668575/examples/ashes3d/index.html?category=sampleModels&model=Buggy&scale=0.02&type=glTF)
![image](https://user-images.githubusercontent.com/1833979/52561808-d1409a00-2e3f-11e9-90a0-51eaa07ee388.png)

[Ashes v0.0.23 + CesiumMilkTruck.gltf result:](https://rawcdn.githack.com/cx20/gltf-test/0cdde6e7ff886cbba0d76ee87d3bc2593e668575/examples/ashes3d/index.html?category=sampleModels&model=CesiumMilkTruck&scale=0.5&type=glTF)
![image](https://user-images.githubusercontent.com/1833979/52561866-f7663a00-2e3f-11e9-94ec-54b25acbbf3d.png)
