### ISSUE TITLE
Color of SimpleMaterial.gltf is incorrect

### ISSUE THREAD

**Issue by cx20** [but0n/Ashes#6]
I tried displaying [SimpleMaterial.gltf](https://github.com/KhronosGroup/glTF-Tutorials/blob/master/gltfTutorial/gltfTutorial_011_SimpleMaterial.md) in the latest version library.
However, the color displayed is different from what you expected.

[Ashes v0.0.18 + SimpleMaterial.gltf result:](https://rawcdn.githack.com/cx20/gltf-test/a74e7cc11bfcafa1eb4328c88e5f8464f8686923/examples/ashes3d/index.html?category=tutorialModels&model=SimpleMaterial&scale=1&type=glTF)
![image](https://user-images.githubusercontent.com/1833979/51784669-d9d27880-218f-11e9-87e3-8e64ff5a7410.png)

The following are assumed results.
![image](https://user-images.githubusercontent.com/1833979/51784664-c58e7b80-218f-11e9-8645-4a47a1f89f37.png)

**Comment by but0n** [comment]
Thanks for your feedback!

This is caused by incorrect normal vector when normals are not specified.
I will add normals calculation feature soon.

![image](https://user-images.githubusercontent.com/7625588/52530413-7116fe80-2d40-11e9-9883-defe4f6f5603.png)

**Comment by but0n** [comment]
It is kind of tricky because the normals calculation function needs *OES_standard_derivatives* which requires **#version 300 es** that iOS doesn't support unless using WebGL 1.0 context.

**Comment by but0n** [comment]
![image](https://user-images.githubusercontent.com/7625588/57570244-87f9e980-7432-11e9-869b-b1ac513a7589.png)

I think it should be fixed in the latest version!

**Comment by cx20** [comment]
I confirmed that it will be displayed in the latest version.

[Ashes v0.2.2 + SimpleMaterial.gltf result:](https://cx20.github.io/gltf-test/examples/ashes3d/index.html?category=tutorialModels&model=SimpleMaterial&scale=1&type=glTF)
![image](https://user-images.githubusercontent.com/1833979/57577323-3774a180-74af-11e9-82e7-4691e04a5ae6.png)
