### ISSUE TITLE
brdfLUT.png is 404 Not Found

### ISSUE THREAD

**Issue by cx20** [but0n/Ashes#60]
I tried the library `0.4.1` in jsDelivr.
https://www.jsdelivr.com/package/npm/ashes3d

However, the referencing `brdfLUT.png` seems to refer to the old path.

**Comment by but0n** [comment]
Thanks for your feedback!

It should be fixed in `0.5.0`.
In the latest version, it will no longer require the brdfLUT, no more 404 error :)

Cheers

**Comment by cx20** [comment]
Thanks. I have confirmed that the problem has been resolved in the latest version.
https://cx20.github.io/gltf-test/examples/ashes3d/index.html?category=tutorialModels&model=DamagedHelmet&scale=1&type=glTF
