### ISSUE TITLE
CesiumMilkTruck.gltf's window glass is transparent is incorrect

### ISSUE THREAD

**Issue by cx20** [but0n/Ashes#8]
I tried to display [CesiumMilkTruck.gltf](https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/CesiumMilkTruck) with Ashes.
However, it is incorrect that the window glass is transparent.

[Ashes v0.0.19 + CesiumMilkTruck.gltf result:](https://rawcdn.githack.com/cx20/gltf-test/cfd8cf36494621902b0f2f9ce0aa08be1469514c/examples/ashes3d/index.html?category=sampleModels&model=CesiumMilkTruck&scale=0.5&type=glTF)
![image](https://user-images.githubusercontent.com/1833979/51787205-49595f80-21b2-11e9-8bba-b1bb2f5e5abd.png)

[three.js r101 + CesiumMilkTruck.gltf result:](https://rawcdn.githack.com/cx20/gltf-test/cfd8cf36494621902b0f2f9ce0aa08be1469514c/examples/threejs/index.html?category=sampleModels&model=CesiumMilkTruck&scale=0.5&type=glTF)
![image](https://user-images.githubusercontent.com/1833979/51787219-71e15980-21b2-11e9-8ac2-08918c9647ea.png)

**Comment by but0n** [comment]
Thanks for your feedback!
I think it probably is related to **AlphaBlendModeTest** which this library haven’t pass yet. I’ll handle this after vacation.

**Comment by cx20** [comment]
I confirmed that the window glass of CesiumMilkTruck.gltf is displayed in the latest version library.

[Ashes v0.0.21 + CesiumMilkTruck.gltf result:](https://rawcdn.githack.com/cx20/gltf-test/9dd14c4d6df4a0ab5977c19e0d2d77eb8364ae17/examples/ashes3d/index.html?category=sampleModels&model=CesiumMilkTruck&scale=0.5&type=glTF)
![image](https://user-images.githubusercontent.com/1833979/52555698-ca109080-2e2d-11e9-8790-5450589b3128.png)
