### ISSUE TITLE
Display result of BoomBoxWithAxes.gltf is different from assumed

### ISSUE THREAD

**Issue by cx20** [but0n/Ashes#9]
[Ashes + BoomBoxWithAxes.gltf result:](https://rawcdn.githack.com/cx20/gltf-test/f3702c5be97091d3a7955f66ed9c3e158d699e2b/examples/ashes3d/index.html?category=tutorialModels&model=BoomBoxWithAxes&scale=80&type=glTF)
![image](https://user-images.githubusercontent.com/1833979/51788510-0bfcce00-21c2-11e9-97b9-4a0f76a3f53c.png)

[three.js + BoomBoxWithAxes.gltf result:](https://rawcdn.githack.com/cx20/gltf-test/f3702c5be97091d3a7955f66ed9c3e158d699e2b/examples/threejs/index.html?category=tutorialModels&model=BoomBoxWithAxes&scale=80&type=glTF)
![image](https://user-images.githubusercontent.com/1833979/51788517-2040cb00-21c2-11e9-87e9-d602606308e6.png)

**Comment by cx20** [comment]
In the model below, the item label is hidden behind. I think it is probably the same cause.
[Ashes + VertexColorTest.gltf result:](https://rawcdn.githack.com/cx20/gltf-test/f3702c5be97091d3a7955f66ed9c3e158d699e2b/examples/ashes3d/index.html?category=tutorialModels&model=VertexColorTest&scale=1&type=glTF)
![image](https://user-images.githubusercontent.com/1833979/51796586-1c508f80-223a-11e9-8433-112ba31f69c6.png)

**Comment by but0n** [comment]
Thanks for your feedback!
![image](https://user-images.githubusercontent.com/7625588/52544493-20f57600-2dec-11e9-9f98-241608aaf96a.png)

**Comment by cx20** [comment]
I confirmed that this issue has been fixed in the latest version of the library.

[Ashes + BoomBoxWithAxes.gltf result:](https://rawcdn.githack.com/cx20/gltf-test/8ef0a1cde7d6a2f8cd44d14a815d208c6baa0ee9/examples/ashes3d/index.html?category=tutorialModels&model=BoomBoxWithAxes&scale=80&type=glTF)
![image](https://user-images.githubusercontent.com/1833979/52547224-768c4b80-2e09-11e9-9f7c-2d67a038e753.png)

[Ashes + VertexColorTestgltf result:](https://rawcdn.githack.com/cx20/gltf-test/8ef0a1cde7d6a2f8cd44d14a815d208c6baa0ee9/examples/ashes3d/index.html?category=tutorialModels&model=VertexColorTest&scale=1&type=glTF)
![image](https://user-images.githubusercontent.com/1833979/52547296-0fbb6200-2e0a-11e9-916c-eb984c593868.png)
